AME:
  Lens:
    low_color: [250, 0, 250]
    high_color: [256, 0, 256]
  Retina:
    low_color: [110, 0, 110]
    high_color: [130, 0, 130]
ALE:
  Lens:
    low_color: [0, 250, 0]
    high_color: [0, 256, 0]
  Retina:
    low_color: [0, 110, 0]
    high_color: [0, 130, 0]
PME:
  Lens:
    low_color: [0, 250, 250]
    high_color: [0, 256, 256]
  Retina:
    low_color: [0, 110, 110]
    high_color: [0, 130, 130]
PLE:
  Lens:
    low_color: [0, 0, 250]
    high_color: [0, 0, 256]
  Retina:
    low_color: [0, 0, 110]
    high_color: [0, 0, 130]

Markers:
  center:
    low_color: [0, 0, 250]
    high_color: [0, 0, 256]
  front:
    low_color: [0, 0, 110]
    high_color: [0, 0, 130]
  back:
    low_color: [ 0, 0, 110 ]
    high_color: [ 0, 0, 130 ]
  top:
    low_color: [ 0, 0, 110 ]
    high_color: [ 0, 0, 130 ]
  bottom:
    low_color: [ 0, 0, 110 ]
    high_color: [ 0, 0, 130 ]
  left:
    low_color: [ 0, 0, 110 ]
    high_color: [ 0, 0, 130 ]
  right:
    low_color: [ 0, 0, 110 ]
    high_color: [ 0, 0, 130 ]